export const CANVAS_CONSTANTS = {
	CANVAS_SIZE: 200000,
	CANVAS_OFFSET: -100000,
	GRID_SIZE: 20,
	DOT_SIZE: 0.5,
	DOT_OPACITY: 1,
	COLORS: {
		GRID_DOT: "var(--grid-dot)",
	},
	ZOOM: {
		MIN: 0.1,
		MAX: 10,
		DEFAULT: 1,
	},
	VIEWPORT: {
		DEFAULT_WIDTH: 0,
		DEFAULT_HEIGHT: 0,
	},
} as const;
